name=ProtoShade-Runtime
version=0.1.0
author=Jefvaia
maintainer=Jefvaia
sentence=ProtoShade Core Runtime for both esp32-s3 and wasm
paragraph=
category=Display
url=https://jefvaia.com
architectures=*
includes=ProtoShadeRuntime.h
